# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jzorreta <jzorreta@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/10/16 16:06:39 by jzorreta          #+#    #+#              #
#    Updated: 2025/10/24 14:27:52 by jzorreta         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


NAME = libft.a

SRCS = *.c

CC = cc

CFLAGS = -Wall -Wextra -Werror

AR = ar rcs

all:
	@echo $(SRCS)

$(NAME):
	
fclean:

clean:

re: